---
- name: ansible v1
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Log in to Docker Hub
      docker_login:
        username: tajbaevsh
        password: qwertySh1

    - name: Build Docker image
      command: docker build -t tajbaevsh/hh_server:latest /home/shama/Desktop/ci-cd

    - name: Push Docker image to Docker Hub
      command: docker push tajbaevsh/hh_server:latest

    - name: display
      command: ls
      register: ls_output
      
    - name: Display kubectl output
      debug:
        var: ls_output.stdout_lines

    - name:  delete deployment.yaml
      command: kubectl delete -f deployment.yaml
      register: delete_output

    - name: Display kubectl output
      debug:
        var: delete_output.stdout_lines

    - name:  apply deployment.yaml
      command: kubectl apply -f deployment.yaml
      register: apply_output
        
    - name: Display kubectl output
      debug:
        var: apply_output.stdout_lines

    - name: Run kubectl command
      command: kubectl get pods 
      register: kubectl_output

    - name: Display kubectl output
      debug:
        var: kubectl_output.stdout_lines

- name: ansible v1
  hosts: servers
  gather_facts: no
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_user: ismoil
    ansible_ssh_pass: Martian123!
    ansible_become_password: Martian123!

  tasks:
    - name: display_server_directory
      command: ls
      register: ls_server_output

    - name: Display server output
      debug:
        var: ls_server_output.stdout_lines

    - name: whoami command
      command: whoami
      register: whoami

    - name: whoami command output
      debug:
        var: whoami.stdout_lines

    - name: add kubernetes file in server  
      template:
        src: /etc/nginx/sites-available/hh.conf
        dest: /etc/nginx/sites-available/

    - name: create a symbolic-link for nginx file
      command: ln -s ../sites-available/hh.conf
      args:
        chdir: /etc/nginx/sites-enabled

    - name: Restart Nginx service
      command: sudo systemctl restart nginx

    - name: nginx restart output
      debug:
        var: nginx_restart.stdout_lines

    - name: Run kubectl command
      command: kubectl get pods 
      register: kubectl_output

    - name: Display kubectl output
      debug:
        var: kubectl_output.stdout_lines

    - name: add kuberntes file in server  
      template:
        src: /home/shama/Desktop/ci-cd/deployment.yaml
        dest: /home/ismoil/Projects