---
- name: ansible v1
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Log in to Docker Hub
      docker_login:
        username: tajbaevsh
        password: qwertySh1

    - name: Build Docker image
      command: docker build -t tajbaevsh/hh_server:latest /home/shama/Desktop/ci-cd

    - name: Push Docker image to Docker Hub
      command: docker push tajbaevsh/hh_server:latest

    - name: display
      command: ls
      register: ls_output
      
    - name: Display kubectl output
      debug:
        var: ls_output.stdout_lines

    - name:  delete deployment.yaml
      command: kubectl delete -f deployment.yaml
      register: delete_output

    - name: Display kubectl output
      debug:
        var: delete_output.stdout_lines

    - name:  apply deployment.yaml
      command: kubectl apply -f deployment.yaml
      register: apply_output
        
    - name: Display kubectl output
      debug:
        var: apply_output.stdout_lines

    - name: Run kubectl command
      command: kubectl get pods 
      register: kubectl_output

    - name: Display kubectl output
      debug:
        var: kubectl_output.stdout_lines

- name: ansible v1
  hosts: servers
  gather_facts: no
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_user: ismoil
    ansible_ssh_pass: Martian123!
    ansible_become_password: Martian123!

  tasks:
    - name: display_server_directory
      command: ls
      register: ls_server_output

    - name: Display server output
      debug:
        var: ls_server_output.stdout_lines

    - name: Create file in project directory
      file:
        path: /etc/nginx/conf.d
        state: directory
        mode: '0755'

    - name: Create the file
      file:
        path: /etc/nginx/sites-available/test
        state: touch
        mode: "0644"
        
    - name: change directory 
      command: ls
      args:
        chdir: /etc/nginx/sites-available
      register: ls_output

    - name: Display server output
      debug:
        var: ls_output.stdout_lines

    # - name: Run kubectl command
    #   command: kubectl get pods 
    #   register: kubectl_output

    # - name: Display kubectl output
    #   debug:
    #     var: kubectl_output.stdout_lines